labels:
  - name: doof
    color: CC0000
    description: works?
  - name: bug
    color: CC0000
    description: Ahhhhh! It's a spider!
  - name: feature
    color: 336699
    description: Don't worry, this repo comes with a fly swatter
  - name: Funny
    color: 123456
    description: Not
